import assert from 'node:assert/strict';
import { CHORD_CATEGORIES, CHORD_LIBRARY, CHORD_ROOTS } from '../src/editor/chord-library.js';
import { nextRibbonSection, RIBBON_SECTIONS } from '../src/editor/ribbon.js';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

assert.equal(nextRibbonSection(null,RIBBON_SECTIONS.TECHNIQUE),RIBBON_SECTIONS.TECHNIQUE);
assert.equal(nextRibbonSection(RIBBON_SECTIONS.TECHNIQUE,RIBBON_SECTIONS.TECHNIQUE),null);
assert.equal(nextRibbonSection(RIBBON_SECTIONS.TECHNIQUE,RIBBON_SECTIONS.CHORD),RIBBON_SECTIONS.CHORD);
assert.deepEqual(CHORD_CATEGORIES.map(item=>item.id),['major','minor','dominant','suspended','other']);
assert.equal(CHORD_ROOTS.length,12);
assert.equal(CHORD_LIBRARY.length,216);
const root=new URL('..',import.meta.url).pathname;
const controller=readFileSync(join(root,'src/editor/controller.js'),'utf8');
const ribbon=readFileSync(join(root,'src/editor/ribbon.js'),'utf8');
const styles=readFileSync(join(root,'styles/editor-tools.css'),'utf8');
assert.match(controller,/onChordSelect: selection => setActiveChord\(selection\)/);
assert.match(controller,/isContinuous\(RIBBON_SECTIONS\.TECHNIQUE\)/);
assert.match(controller,/isContinuous\(RIBBON_SECTIONS\.CHORD\)/);
assert.match(ribbon,/createContinuousButton\(RIBBON_SECTIONS\.TECHNIQUE\)/);
assert.match(ribbon,/createContinuousButton\(RIBBON_SECTIONS\.CHORD\)/);
assert.match(ribbon,/onChordSelect\?\.\(\{ chordId:/);
assert.match(ribbon,/draggable = true/,'clickable chords must remain draggable too');
assert.match(styles,/\.editor-ribbon-tab\{[^}]*background:#1ed760/s);
assert.match(styles,/\.editor-continuous-button/);
assert.match(styles,/\.editor-chord-button\.is-active/);
assert.doesNotMatch(styles,/\.editor-toolbox|\.note-input/);
console.log('editor ribbon tests passed');
