import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { artistProfileFor } from '../src/catalog/artist-profiles.js';

const browser=await readFile(new URL('../src/catalog/song-browser.js',import.meta.url),'utf8');
const catalogCss=await readFile(new URL('../styles/catalog.css',import.meta.url),'utf8');
const editorCss=await readFile(new URL('../styles/editor-v3.css',import.meta.url),'utf8');
const moduleCss=await readFile(new URL('../styles/editor-modules.css',import.meta.url),'utf8');
const adaptiveCss=await readFile(new URL('../styles/adaptive-measures.css',import.meta.url),'utf8');
const toolsCss=await readFile(new URL('../styles/editor-tools.css',import.meta.url),'utf8');
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');

assert.equal(artistProfileFor('周杰倫')?.image,'https://r2.theaudiodb.com/images/media/artist/thumb/1xuf2r1779253287.jpg');
assert.doesNotMatch(browser,/installHorizontalWheel|preventDefault\(\).*scrollLeft/s,'rails must not hijack vertical wheel scrolling');
assert.match(browser,/work-card-inner/);
assert.match(browser,/work-card-front/);
assert.match(browser,/work-card-back/);
assert.match(browser,/點擊展開/);
assert.match(browser,/顯示所有內容/);
assert.match(catalogCss,/\.song-browser-next\{[^}]*width:42px[^}]*height:42px[^}]*opacity:0/s);
assert.match(catalogCss,/\.song-browser-rail-shell:hover>\.song-browser-next/,'next control appears on hover');
assert.match(catalogCss,/\.song-browser-rail\s*\{[^}]*grid-template-rows:repeat\(2,318px\)/s);
assert.match(catalogCss,/\.song-browser-artist-rail\s*\{[^}]*grid-template-rows:1fr/s);
assert.doesNotMatch(html,/PUBLIC CATALOG/);
assert.match(html,/class="library-hero-copy"/);
assert.match(html,/class="library-hero-controls"/);
assert.match(editorCss,/\.v3-column-target\{[^}]*z-index:4/s);
assert.match(editorCss,/\.v3-note-backdrop\{[^}]*z-index:6/s);
assert.match(editorCss,/\.v3-note\{[^}]*z-index:8/s,'number text must always sit above white note backdrops');
assert.match(moduleCss,/\.content\.edit-view \.editor-row-module:hover,\.content\.edit-view \.editor-row-module\.is-selected\{border-color:#1ed760/s);
assert.match(adaptiveCss,/\.content\.score-view \.adaptive-layout-stack\{grid-column:2\}/);
assert.match(toolsCss,/\.notation-overlay\{z-index:10\}/);
assert.match(toolsCss,/\.notation-relation\{[^}]*fill:none!important/s,'arcs must be stroked paths rather than filled semicircles');
assert.match(toolsCss,/\.editor-ribbon-tab\{[^}]*background:#1ed760/s);
assert.match(toolsCss,/\.editor-continuous-button\{[^}]*background:#1ed760/s);
console.log('UI layout regression tests passed');
