import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { artistProfileFor } from '../src/catalog/artist-profiles.js';

const browser=await readFile(new URL('../src/catalog/song-browser.js',import.meta.url),'utf8');
const catalogCss=await readFile(new URL('../styles/catalog.css',import.meta.url),'utf8');
const editorCss=await readFile(new URL('../styles/editor-v3.css',import.meta.url),'utf8');
const moduleCss=await readFile(new URL('../styles/editor-modules.css',import.meta.url),'utf8');
const adaptiveCss=await readFile(new URL('../styles/adaptive-measures.css',import.meta.url),'utf8');
const toolsCss=await readFile(new URL('../styles/editor-tools.css',import.meta.url),'utf8');
const responsiveCss=await readFile(new URL('../styles/responsive.css',import.meta.url),'utf8');
const headerCss=await readFile(new URL('../styles/header.css',import.meta.url),'utf8');
const structure=await readFile(new URL('../src/editor/structure-controller.js',import.meta.url),'utf8');
const renderer=await readFile(new URL('../src/editor/renderer.js',import.meta.url),'utf8');
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');

assert.equal(artistProfileFor('周杰倫')?.image,'https://r2.theaudiodb.com/images/media/artist/thumb/1xuf2r1779253287.jpg');
assert.doesNotMatch(browser,/installHorizontalWheel|preventDefault\(\).*scrollLeft/s,'rails must not hijack vertical wheel scrolling');
assert.match(browser,/work-card-inner/);
assert.match(browser,/work-card-front/);
assert.match(browser,/work-card-back/);
assert.match(browser,/點擊展開/);
assert.match(browser,/顯示所有內容/);
assert.doesNotMatch(browser,/values\.push\(`Capo /,'flipped card metadata must not show capo');
assert.doesNotMatch(browser,/values\.push\(`\$\{Number\(arrangement\.tempo\).*BPM/,'flipped card metadata must not show BPM');
assert.match(catalogCss,/\.song-browser-next\{[^}]*width:42px[^}]*height:42px[^}]*opacity:0/s);
assert.match(catalogCss,/\.song-browser-rail-shell:hover>\.song-browser-next/,'next control appears on hover');
assert.match(catalogCss,/\.song-browser-rail\s*\{[^}]*grid-template-rows:repeat\(2,318px\)/s);
assert.match(catalogCss,/\.song-browser-artist-rail\s*\{[^}]*grid-template-rows:1fr/s);
assert.doesNotMatch(html,/PUBLIC CATALOG|OPEN TAB LIBRARY|YOUR LIBRARY/,'catalog/library hero should not show redundant English eyebrow labels');
assert.match(html,/class="library-hero-copy"/);
assert.match(html,/class="library-hero-controls"/);
assert.match(editorCss,/\.v3-column-target\{[^}]*z-index:4/s);
assert.match(editorCss,/\.v3-note-backdrop\{[^}]*z-index:6/s);
assert.match(editorCss,/\.v3-note\{[^}]*z-index:8/s,'number text must always sit above white note backdrops');
assert.match(moduleCss,/\.content\.edit-view \.editor-row-module:hover,\.content\.edit-view \.editor-row-module\.is-selected\{border-color:#1ed760/s);
assert.match(moduleCss,/\.visual-row-handle\{[^}]*flex-direction:column[^}]*gap:7px/s,'wrapped visual rows must expose the same vertical action rail');
assert.match(structure,/function makeRowHandle\(target,/,'every visual row must use the same row handle implementation');
assert.match(structure,/grip\.textContent = '⠿'/,'every visual row must show the six-dot drag indicator');
assert.match(structure,/measureIdsForSystem\(system\)/,'row actions must target the measures visible in that wrapped row');
assert.match(structure,/deleteMeasures\(documentModel, target\.measureIds\)/,'deleting a wrapped row must delete only its visible measures');
assert.match(adaptiveCss,/\.content\.score-view \.adaptive-layout-stack\{grid-column:2\}/);
assert.match(toolsCss,/\.notation-overlay\{z-index:10\}/);
assert.match(toolsCss,/\.notation-relation\{[^}]*fill:none!important/s,'arcs must be stroked paths rather than filled semicircles');
assert.match(toolsCss,/\.editor-ribbon-tab\{[^}]*background:#1ed760/s);
assert.match(toolsCss,/\.editor-continuous-button\{[^}]*background:#1ed760/s);
assert.match(responsiveCss,/grid-template-columns:minmax\(0,1\.2fr\) minmax\(0,1fr\) minmax\(0,\.85fr\)/,'mobile playback controls must stay inside the viewport');
assert.match(responsiveCss,/\.editor-ribbon\{[^}]*contain:inline-size/s,'expanded ribbon must not change editor intrinsic width');
assert.match(responsiveCss,/\.editor-ribbon-section\{[^}]*overflow-x:auto[^}]*touch-action:pan-x/s,'mobile ribbon must support native horizontal swiping');
assert.match(responsiveCss,/\.mobile-menu-button\{position:absolute/,'mobile navigation button must scroll with the page instead of covering titles');
assert.match(responsiveCss,/\.catalog-view,\.library-view\{position:relative;padding-top:88px\}/,'mobile catalog must reserve space above the title');
assert.match(renderer,/Math\.min\(\.\.\.candidates\)/,'adaptive layout width must be capped by the visible viewport');
assert.match(renderer,/createRhythmLayer\(measure, visualTimeByKey\)/,'score renderer must draw rhythm stems and beams');
assert.match(renderer,/v3-rhythm-stem/);
assert.match(renderer,/v3-rhythm-beam/);
assert.match(headerCss,/\.preview-badge \{ display:none!important; \}/,'public preview subtitle badge should not be visible');
console.log('UI layout regression tests passed');
