import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { artistProfileFor } from '../src/catalog/artist-profiles.js';

const browser=await readFile(new URL('../src/catalog/song-browser.js',import.meta.url),'utf8');
const appCatalog=await readFile(new URL('../src/app-catalog.js',import.meta.url),'utf8');
const catalogCss=await readFile(new URL('../styles/catalog.css',import.meta.url),'utf8');
const editorCss=await readFile(new URL('../styles/editor-v3.css',import.meta.url),'utf8');
const moduleCss=await readFile(new URL('../styles/editor-modules.css',import.meta.url),'utf8');
const adaptiveCss=await readFile(new URL('../styles/adaptive-measures.css',import.meta.url),'utf8');
const toolsCss=await readFile(new URL('../styles/editor-tools.css',import.meta.url),'utf8');
const responsiveCss=await readFile(new URL('../styles/responsive.css',import.meta.url),'utf8');
const scoreCss=await readFile(new URL('../styles/score-layout.css',import.meta.url),'utf8');
const headerCss=await readFile(new URL('../styles/header.css',import.meta.url),'utf8');
const structure=await readFile(new URL('../src/editor/structure-controller.js',import.meta.url),'utf8');
const renderer=await readFile(new URL('../src/editor/renderer.js',import.meta.url),'utf8');
const notation=await readFile(new URL('../src/editor/notation-renderer.js',import.meta.url),'utf8');
const html=await readFile(new URL('../index.html',import.meta.url),'utf8');

assert.equal(artistProfileFor('周杰倫')?.image,'https://r2.theaudiodb.com/images/media/artist/thumb/1xuf2r1779253287.jpg');
assert.doesNotMatch(browser,/installHorizontalWheel|addEventListener\(['"]wheel['"]/,'rails must not hijack vertical wheel scrolling');
assert.match(browser,/work-card-inner/);
assert.match(browser,/work-card-front/);
assert.match(browser,/work-card-back/);
assert.match(browser,/點擊展開/);
assert.match(browser,/顯示所有曲譜/);
assert.doesNotMatch(browser,/work-card-toggle|收合/,'flipped cards close by clicking the card, not a redundant collapse button');
assert.match(browser,/updateRailButtons\(rail, prev, next\)/,'rail navigation must derive arrows from real scroll boundaries');
assert.doesNotMatch(browser,/values\.push\(`Capo /,'flipped card metadata must not show capo');
assert.doesNotMatch(browser,/values\.push\(`\$\{Number\(arrangement\.tempo\).*BPM/,'flipped card metadata must not show BPM');
assert.match(appCatalog,/work-card-preview-icon/,'catalog preview action must use the eye icon');
assert.match(appCatalog,/createArrangementMenu/,'catalog management actions must live in the compact more menu');
assert.match(catalogCss,/\.song-browser-nav\{[^}]*width:42px[^}]*height:42px[^}]*opacity:0/s);
assert.match(catalogCss,/\.song-browser-rail-shell:hover>\.song-browser-nav:not\(\[hidden\]\)/,'rail controls appear only on hover/focus');
assert.match(catalogCss,/\.song-browser-rail\s*\{[^}]*grid-template-rows:repeat\(2,344px\)[^}]*min-height:706px/s,'catalog cards need enough vertical room for title and metadata');
assert.match(catalogCss,/@media\(max-width:900px\)[\s\S]*\.song-browser-rail\{[^}]*grid-template-rows:repeat\(2,324px\)[^}]*min-height:666px/s,'mobile catalog cards need enough vertical room for the title');
assert.match(catalogCss,/\.song-card-body h3,\.work-card-back-copy h3\{[^}]*min-height:1\.3em[^}]*flex:0 0 auto[^}]*line-height:1\.3/s,'song title must not shrink into a clipped line');
assert.match(catalogCss,/\.song-browser-artist-rail\s*\{[^}]*grid-template-rows:1fr/s);
assert.doesNotMatch(html,/PUBLIC CATALOG|OPEN TAB LIBRARY|YOUR LIBRARY/,'catalog/library hero should not show redundant English eyebrow labels');
assert.doesNotMatch(html,/<h2>公共曲譜<\/h2>/,'catalog must not repeat a public-catalog section title');
assert.match(html,/class="library-hero-copy"/);
assert.match(html,/class="library-hero-controls"/);
assert.match(editorCss,/\.v3-column-target\{[^}]*z-index:4/s);
assert.match(editorCss,/\.v3-note-backdrop\{[^}]*z-index:6/s);
assert.match(editorCss,/\.v3-note\{[^}]*z-index:8/s,'number text must always sit above white note backdrops');
assert.match(editorCss,/\.content\.score-view \.v3-staff\{[^}]*top:12px[^}]*bottom:calc\(var\(--rhythm-height,36px\) \+ 10px\)[^}]*min-height:0/s,'score staff must reserve a dedicated rhythm lane below the sixth string');
assert.match(editorCss,/\.v3-playback-beat\{[^}]*border-radius:9px[^}]*background:rgba\(30,215,96,\.16\)/s,'playback cursor must be a rounded light-green beat bar');
assert.match(editorCss,/\.v3-rhythm-beam-1\{top:20px\}\.v3-rhythm-beam-2\{top:14px\}\.v3-rhythm-beam-3\{top:8px\}/,'eighth, sixteenth and thirty-second notes need one, two and three beam levels');
assert.match(moduleCss,/\.content\.edit-view \.editor-row-module:hover,\.content\.edit-view \.editor-row-module\.is-selected\{border-color:#1ed760/s);
assert.match(moduleCss,/\.visual-row-handle\{[^}]*flex-direction:column[^}]*gap:7px/s,'wrapped visual rows must expose the same vertical action rail');
assert.match(moduleCss,/\.row-module-label\{[^}]*width:1\.7em[^}]*white-space:normal[^}]*word-break:keep-all[^}]*writing-mode:horizontal-tb/s,'two-digit row numbers must stay together on one horizontal line');
assert.match(structure,/function makeRowHandle\(target,/,'every visual row must use the same row handle implementation');
assert.match(structure,/grip\.textContent = '⠿'/,'every visual row must show the six-dot drag indicator');
assert.match(structure,/measureIdsForSystem\(system\)/,'row actions must target the measures visible in that wrapped row');
assert.match(structure,/deleteMeasures\(documentModel, target\.measureIds\)/,'deleting a wrapped row must delete only its visible measures');
assert.match(adaptiveCss,/\.content\.score-view \.adaptive-layout-stack\{grid-column:2\}/);
assert.match(toolsCss,/\.notation-overlay\{z-index:10\}/);
assert.match(toolsCss,/\.notation-relation\{[^}]*fill:none!important/s,'arcs must be stroked paths rather than filled semicircles');
assert.match(toolsCss,/\.editor-ribbon-tab\{[^}]*background:#1ed760/s);
assert.match(toolsCss,/\.editor-continuous-button\{[^}]*background:#1ed760/s);
assert.match(toolsCss,/\.editor-ribbon-panel\{[^}]*width:max-content[^}]*max-width:100%/s,'tool panel border must shrink-wrap its contents');
assert.match(responsiveCss,/grid-template-columns:minmax\(0,1\.2fr\) minmax\(0,1fr\) minmax\(0,\.85fr\)/,'mobile playback controls must stay inside the viewport');
assert.match(responsiveCss,/\.editor-ribbon\{[^}]*width:max-content[^}]*max-width:100%/s,'mobile ribbon must shrink-wrap instead of spanning the score width');
assert.match(responsiveCss,/\.editor-ribbon-section\{[^}]*width:max-content[^}]*overflow-x:auto[^}]*touch-action:pan-x/s,'mobile ribbon must support native horizontal swiping');
assert.match(responsiveCss,/\.mobile-menu-button\{position:absolute/,'mobile navigation button must scroll with the page instead of covering titles');
assert.match(responsiveCss,/\.catalog-view,\.library-view\{position:relative;padding-top:88px\}/,'mobile catalog must reserve space above the title');
assert.match(renderer,/Math\.min\(\.\.\.candidates\)/,'adaptive layout width must be capped by the visible viewport');
assert.match(renderer,/createRhythmLayer\(measure, visualTimeByKey\)/,'score renderer must draw rhythm stems and beams');
assert.match(renderer,/v3-rhythm-tuplet-number/,'triplet number belongs to the beamed rhythm layer');
assert.match(renderer,/harmonicTechnique\(note\)/,'harmonic display must distinguish edit and score modes');
assert.match(renderer,/initialValue: this\.cursorValueAt/,'arrow navigation must preserve existing note values');
const cursorSource=renderer.slice(renderer.indexOf('showCursor({'),renderer.lastIndexOf('\n}'));
assert.ok(cursorSource.indexOf('this.cursor.blur()')>=0,'continuous editing must commit an existing cell before switching');
assert.ok(cursorSource.indexOf('this.cursor.blur()')<cursorSource.indexOf('const measureNode ='),'continuous editing must resolve the next cell from the live DOM after the previous commit rerenders');
assert.match(cursorSource,/const originalValue = normalizeFret\(initialValue\)[\s\S]*const nextValue = normalizeFret\(input\.value\)[\s\S]*if \(nextValue === originalValue\) return;/,'unchanged keyboard navigation must not rewrite or erase existing notes');
assert.doesNotMatch(notation,/appendRhythmBracket/,'triplet and 32nd subdivision must not render separate bracket labels');
assert.match(notation,/staffTopInSystem/,'chord labels must use a dedicated lane above string one');
assert.match(scoreCss,/\.content\.score-view \.score-density-line\{[^}]*gap:0/s,'compact score segments must join without horizontal gaps');
assert.match(headerCss,/\.preview-badge \{ display:none!important; \}/,'public preview subtitle badge should not be visible');
console.log('UI layout regression tests passed');