import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app=await readFile(new URL('../src/app-catalog.js',import.meta.url),'utf8');
const browser=await readFile(new URL('../src/catalog/song-browser.js',import.meta.url),'utf8');
const runtime=await readFile(new URL('../src/app-runtime.js',import.meta.url),'utf8');
const catalogCss=await readFile(new URL('../styles/catalog.css',import.meta.url),'utf8');
const mainCss=await readFile(new URL('../styles/main.css',import.meta.url),'utf8');
assert.match(runtime,/let catalogWorks = \[\]/);
assert.doesNotMatch(runtime,/catalogSongs/);
assert.match(app,/Array\.isArray\(result\.works\) \? result\.works : \[\]/);
assert.match(browser,/createWorkCard\(work\)/);
assert.match(browser,/createArrangementRow\(work, arrangement\)/);
assert.match(browser,/work-card-style-badges/);
assert.match(browser,/difficultyLabel\(arrangement\.difficulty\)/);
assert.doesNotMatch(app,/catalog-card-more|catalog-card-menu|catalogMenuOpenFor/);
assert.doesNotMatch(mainCss,/catalog-management\.css/);
const cardSource=browser.slice(browser.indexOf('createWorkCard(work)'),browser.indexOf('syncRailControls'));
assert.doesNotMatch(cardSource,/difficultyLabel|難度/,'outer WorkCard summary must not own difficulty');
assert.match(app,/'預覽'/);
assert.match(app,/'編輯'/);
assert.match(app,/'下架'/);
assert.match(app,/'＋ 加入'/);
assert.doesNotMatch(catalogCss,/\.work-card\.is-expanded\s*\{[^}]*grid-row|grid-column:span/s,'flipped card must keep its original rail footprint');
assert.match(catalogCss,/\.work-card\.is-expanded \.work-card-inner\s*\{[^}]*rotateY\(180deg\)/s);
assert.match(catalogCss,/\.work-card-arrangements\s*\{[^}]*overflow:auto/s,'fixed-size back face must scroll internally when needed');
assert.match(catalogCss,/\.work-card-front \.work-card-style-badges\s*\{[^}]*margin-bottom:12px/s,'style badge must have breathing room at the card bottom');
console.log('WorkCard preview tests passed');
