import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app=await readFile(new URL('../src/app-catalog.js',import.meta.url),'utf8');
const browser=await readFile(new URL('../src/catalog/song-browser.js',import.meta.url),'utf8');
const runtime=await readFile(new URL('../src/app-runtime.js',import.meta.url),'utf8');
const catalogCss=await readFile(new URL('../styles/catalog.css',import.meta.url),'utf8');
const mainCss=await readFile(new URL('../styles/main.css',import.meta.url),'utf8');
const library=await readFile(new URL('../src/app-library.js',import.meta.url),'utf8');
assert.match(runtime,/let catalogWorks = \[\]/);
assert.doesNotMatch(runtime,/catalogSongs/);
assert.match(app,/Array\.isArray\(result\.works\) \? result\.works : \[\]/);
assert.match(browser,/createWorkCard\(work\)/);
assert.match(browser,/createArrangementRow\(work, arrangement\)/);
assert.match(browser,/work-card-style-badges/);
assert.match(browser,/difficultyLabel\(arrangement\.difficulty\)/);
assert.doesNotMatch(app,/catalog-card-more|catalog-card-menu|catalogMenuOpenFor/);
assert.doesNotMatch(mainCss,/catalog-management\.css/);
const cardSource=browser.slice(browser.indexOf('createWorkCard(work)'),browser.indexOf('updateRailButtons'));
assert.doesNotMatch(cardSource,/difficultyLabel|難度/,'outer WorkCard summary must not own difficulty');
assert.match(app,/work-card-preview-icon/,'preview action must be an eye icon button');
assert.match(app,/createArrangementMenu/,'edit and visibility actions must share the compact ellipsis menu');
assert.match(app,/'編輯'/);
assert.match(app,/'下架'/);
assert.match(app,/'＋ 加入'/);
assert.match(library,/badge\.textContent = '未上架';/,'unlisted personal scores must use the 未上架 label');
assert.doesNotMatch(library,/badge\.textContent = '已下架';/,'the old 已下架 badge label must not remain');
assert.match(catalogCss,/\.song-hidden-badge\{[^}]*width:max-content[^}]*max-width:max-content[^}]*flex:0 0 auto[^}]*white-space:nowrap/s,'the unlisted badge must shrink to its content instead of stretching across the sidebar');
const libraryActions=app.slice(app.indexOf('function renderLibraryArrangementActions'),app.indexOf('function ensureLibrarySearchInput'));
assert.match(libraryActions,/work-card-action primary work-card-action-icon work-card-edit-icon/,'library edit must use the shared green circular icon button');
assert.match(libraryActions,/createArrangementMenu\(menuItems\)/,'library visibility and delete actions must use the shared ellipsis menu');
assert.match(libraryActions,/label: isPublic \? '下架' : '重新上架'/,'library visibility action must stay available inside the menu');
assert.match(libraryActions,/label: '刪除', danger: true/,'library delete must stay available as a danger menu item');
assert.doesNotMatch(libraryActions,/actionButton\('編輯'|actionButton\('刪除'/,'library must not render standalone text edit/delete buttons');
assert.doesNotMatch(browser,/work-card-toggle|收合/,'back face must not include a redundant collapse button');
assert.doesNotMatch(catalogCss,/\.work-card\.is-expanded\s*\{[^}]*grid-row|grid-column:span/s,'flipped card must keep its original rail footprint');
assert.match(catalogCss,/\.work-card\.is-expanded \.work-card-inner\s*\{[^}]*rotateY\(180deg\)/s);
assert.match(catalogCss,/\.work-card\.is-expanded \.work-card-back\{pointer-events:auto\}/,'back-face actions must remain clickable after the 3D flip');
assert.match(catalogCss,/\.work-card-arrangements\s*\{[^}]*overflow:auto/s,'fixed-size back face must scroll internally when needed');
assert.match(catalogCss,/\.work-card-front \.work-card-style-badges\s*\{[^}]*margin-bottom:12px/s,'style badge must have breathing room at the card bottom');
console.log('WorkCard preview tests passed');